[advisories]
ignore = [
  "RUSTSEC-2024-0388", # derivative unmaintained - keeping original ignore
  "RUSTSEC-2024-0436", # paste unmaintained - used by wasmer 6.1.0
]

[output]
quiet = false  # Show all warnings so we can track progress

