node:
  id: "ArthaXccafe81481e0ea21c311"
  type: "rpc"
  role: "api"

network:
  p2p:
    port: 8087
  api:
    port: 8083
  metrics:
    port: 9187

api:
  rate_limiting: true
  max_connections: 1000
