apiVersion: v1
kind: Namespace
metadata:
  name: arthachain
  labels:
    name: arthachain
    environment: production

---
apiVersion: v1
kind: Namespace
metadata:
  name: arthachain-staging
  labels:
    name: arthachain
    environment: staging

