[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc_version = '0.8.24'
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200
bytecode_hash = 'ipfs'
fuzz_runs = 256
ffi = true
via_ir = true

[invariant]
runs = 128
depth = 256
fail_on_revert = true
call_override = false

[fmt]
line_length = 100
tab_width = 4


